travis:
  secure:
    BINSTAR_TOKEN: rk+Sx7Sn40L4ivM/mzhl/Xb4YBsKaafSnPan9k6tUPILpPoqoPvikCA9uJCepVROa92/UL/UioSUVlLMb4gOpAOgJxZMUQnpmYQH4kMMDqiHiBD0gD1EEIPaSCz3XZG0Vlb784ELuMlXGaoyXOxCISUqZ98oC1jVbDjZlzsLYFDi6uhqZK+bqEK9iZls1tvS48P7aMXhXvK7ZBJ90rmoEa2TZKCcHqdp2wQV+zvQLCNFh9vheUEuGPOjKcK+JXJQOeBpHEbVlu7U/H0nQuWWvzJAEJfgb+VDVmnU5AGBe10n/9u/SVCvxxxsx3Wj1s9OuJJGzEmERUDAMObK0JHhkkegHjdlVfCd/CLjwnxFguY4h78YFKs0ujPZX8qo+xd52kVCEzjyV/hBGBeb8HBqPRorgRSrf/t3b57mNPNDulp6r2X1VhCzlmfLeB+Cbmx3PjuxXG4mnRezMvCU5pXVslaZgD3tHwNeBlWDGc23jhPhVukSqWjIrTfiewORaPrMTY7pN0JBa6cUZeihbJ7oaWIoRO0bU3xGsB6wgFDZAdqKJR3bsvFrOenc5E37MI6Bms430OuOIANEq3YBPcJNmgbhn9ZdBa1X92dPrXNqDY0LAQ6PIdZrkY//TUmkapvcLuEdydoKhzM1Bimf7a71rfgt+//tYv4Q1nmCEp3aJys=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
